CREATE TABLE bet (
    bet_id VARCHAR(64) PRIMARY KEY,
    user_id VARCHAR(64) NOT NULL,
    event_id VARCHAR(64) NOT NULL,
    event_market_id VARCHAR(64) NOT NULL,
    event_winner_id VARCHAR(64) NOT NULL,
    bet_amount DECIMAL(19, 2) NOT NULL,
    CONSTRAINT chk_bet_amount_positive CHECK (bet_amount > 0),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_bet_event_id_bet_id ON bet (event_id, bet_id);

CREATE TABLE processed_event_outcome (
    event_id VARCHAR(64) PRIMARY KEY,
    event_name VARCHAR(255) NOT NULL,
    event_winner_id VARCHAR(64) NOT NULL,
    processed_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE settlement_audit (
    audit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id VARCHAR(64) NOT NULL,
    bet_id VARCHAR(64) NOT NULL,
    user_id VARCHAR(64) NOT NULL,
    settlement_result VARCHAR(16) NOT NULL,
    destination_topic VARCHAR(128) NOT NULL,
    payload_snapshot VARCHAR(4096) NOT NULL,
    publish_status VARCHAR(16) NOT NULL,
    published_at TIMESTAMP WITH TIME ZONE,
    failure_reason VARCHAR(512),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_settlement_audit_event_bet UNIQUE (event_id, bet_id),
    CONSTRAINT chk_settlement_audit_result CHECK (settlement_result IN ('WIN', 'LOSE')),
    CONSTRAINT chk_settlement_audit_publish_status CHECK (publish_status IN ('PENDING', 'SENT', 'FAILED')),
    CONSTRAINT fk_settlement_audit_bet
        FOREIGN KEY (bet_id) REFERENCES bet (bet_id)
);

CREATE INDEX idx_settlement_audit_status_created_bet
    ON settlement_audit (publish_status, created_at, bet_id);

